name: inform
description: A flutter widget library, which provides you some widgets to inform users and let them interact with it.
version: 0.0.1
homepage: https://github.com/elbeicktalat/flutter_inform

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0